Fix/download link
ONSdigital/dp-cantabular-csv-exporter pull request #24
Opened 2021-09-02 15:51 UTC by DavidSubiros

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2021-09-06 15:44 UTC, daiLlew approved these changes
LGTM

2021-09-13 12:49 UTC, redhug1 requested changes
service/initialise.go
line 96, 'New' is deprecated
… which i don’t quite understand, but is apparently a problem ?

handler/handler_test.go
line 126, Variable ‘len’ collides with the builtin function

handler/handler.go
line 95, Variable 'len' collides with the builtin function
lines 209, 217: Unhandled error
line 355, Variable 'bytes' collides with imported package name

-=-=-
handler/handler.go:160:3: assignOp: replace `expectedNumValues = expectedNumValues * dim.Count` with `expectedNumValues *= dim.Count` (gocritic)
		expectedNumValues = expectedNumValues * dim.Count
		^
handler/handler.go:253:3: assignOp: replace `index = index / dims[i].Count` with `index /= dims[i].Count` (gocritic)
		index = index / dims[i].Count               // Modify index for next iteration
		^

2021-09-13 13:39 UTC, DavidSubiros commented
thanks, updated

2021-09-13 14:23 UTC, redhug1 approved these changes

2021-09-13 14:27 UTC, merged